import Navbar from "@/components/Navbar";
import "./global.css";
import AuthNavbar from "@/components/AuthNavbar";
import Link from "next/link";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="bg-black text-white flex justify-between">
          
          <Navbar></Navbar>
          <h1 className="font-bold text-3xl p-3"><Link href='/'>Header</Link></h1>
          <AuthNavbar></AuthNavbar>
        </header>
        <div className="min-h-[81vh]">{children}</div>
        <footer className="bg-black text-white">
          <h1 className="font-bold text-3xl text-center p-3">Footer</h1>
        </footer>
      </body>
    </html>
  );
}
